### ISSUE TITLE
Bundling for Node (to npm publish)

### ISSUE THREAD

**Issue by coryarmbrecht** [egoist/poi.js.org#4]
Thanks for a great project, it has saved me a ton of time for local dev, getting webpack out of the way. Recently I developed some things with Poi that work on clientside that I'm trying to bundle to publish on npm. These are es6 modules that import .scss files and other npm modules.

How do I do that with Poi?  I've done poi build which runs a bundle, but it looks like it's for browsers and setup for the index.ejs. In .babelrc I tried something like:
```
"presets": [
        ["env",
            {
                "targets": {
                    "node": "current",
                    "browsers": "last 1 major version"
                }
            }
        ],
        "react"
    ]
```
but it didn't seem to work. Also it just transpiled the es6 and import stuff, and didn't seem to include the imported npm files.

Will it bundle and rollup everything starting from the entry file? I noticed it separates vendor files from my custom one, but I don't know how / where to [set vendor to false](https://github.com/egoist/poi.js.org/search?utf8=%E2%9C%93&q=vendor&type=). Via the command line?

Thanks!
Cory

**Comment by egoist** [comment]
Here's an option [`library`](https://poi.js.org/#/options?id=library) for bundling libraries in `poi>=9.6.3`:

Either use it as a CLI flag: `poi build --library` or set it in config file:

```js
// poi.config.js
module.exports = {
  library: true
}
```

This option is equivalent to using following options:

```js
// poi.config.js
module.exports = {
  format: 'cjs',
  html: false,
  sourceMap: false
}
```

If you set it to a string like: `library: 'ModuleName'`, it will be equivalent to:

```js
// poi.config.js
module.exports = {
  format: 'umd',
  moduleName: 'ModuleName',
  html: false,
  sourceMap: false
}
```

When `format` is set the `vendor` option will default to `false`.

**Comment by coryarmbrecht** [comment]
What a great project, it works wonderfully. I had to add a few things, such as `extractCSS: false` to get the sass bundled into the js module.

One last question, and I think it makes sense to leave on this issue as it's the same topic. How can I set it up the production / development configs? Currently I have to manually edit the poi.config.js every time I want to switch from `poi` for local testing to `poi build` for publishing modules.

poi
```
module.exports = {
    entry: 'src/index.js',
    format: 'umd',
    html: true,
    sourceMap: true,
    filename: {
        js: 'index.js'
    },
}
```

poi build
```
module.exports = {
    entry: 'src/index.js',
    format: 'cjs',
    html: false,
    sourceMap: false,
    filename: {
        js: 'dist/index.js'
    },
    extractCSS: false
}
```


Something like?:
```
module.exports = [
development: {
    entry: 'src/index.js',
    format: 'umd',
    html: true,
    sourceMap: true,
    filename: {
        js: 'index.js'
    },
},
 production: {
    entry: 'src/index.js',
    format: 'cjs',
    html: false,
    sourceMap: false,
    filename: {
        js: 'dist/index.js'
    },
    extractCSS: false
}
]
```
?

Thanks again!

**Comment by egoist** [comment]
> I had to add a few things, such as extractCSS: false to get the sass bundled into the js module.

I always extract the CSS even it's a library to make the library smaller 😄 But that also depends on specific use case so we didn't disable `extractCSS`.

> How can I set it up the production / development configs?

There're various ways of doing this:

see the doc [the config can be a function which accepts CLI flags as the first argument](https://github.com/egoist/poi.js.org/blob/master/docs/README.md#config-file)

```js
// poi.config.js
module.exports = options => {
    // `options.mode` is auto injected
	const isProd = options.mode === 'production'
	return {
		format: isProd ? 'cjs' : 'umd'
	}
}
```

You can also use any CLI flag (not recommended though)

eg. You can run poi with `--someCondition` then in config file:

```js
module.exports = options => {
  return {
    someOption: options.someCondition ? 'this' : 'that'
  }
}
```

**Comment by egoist** [comment]
Closing since it's solved.
